server:
  port: 8080

spring:
  application:
    name: routes

logging:
  level:
    com.bcf.routes: info

feign:
  client:
    config:
      countries:
        decoder: com.bcf.routes.remote.client.CountriesDecoder
        connectionTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

springdoc:
  packages-to-scan: com.bcf.routes
  swagger-ui:
    path: /api-doc
    operations-sorter: method
    tags-sorter: alpha